server:
  port: 8080
  servlet:
    context-path: /app

spring:
  application:
    name: SystemManagemntApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/Employees
    username: postgres
    password: achraf
    driver-class-name: org.postgresql.Driver

